/*! \page Sample_Run 
  \section install Install
  
  Clone the git repository to a known directory.\n
  cd directory \n
  mkdir build \n
  cd build \n
  cmake ../ \n
  make \n
  
  \section configure Configure
  The main configuration for Sabina is located in data/conf witch contains architecture configurations like ports, maps and positions \n
  Also each test has a custom configuration located in "data/test_name" (e.g. data/who_is_who) this conf is used to configure the modules to load for this test 0=do not load, 1=load and execute.\n
  For each test ther should also be a "data/test_name.ADD" file that is generated by SPUDD (by Dr. Jesse Hoey http://www.cs.uwaterloo.ca/~jhoey/research/spudd/index.php) from a file named "data/test_name.dat" \n
  
  \section run Run
  Since the GUI uses opengl for its display make shure you have configured the apropiated drivers for your hardware \n
  Also in our case we run the test as root for permissions to /dev/ttyUSB* you can change this by changing the apropiated permissions for your devices.\n
  \subsection Optimus Optimus
  If your computer uses optimus capabilities you must: \n
  su \n
  bumblebeed --daemon \n
  cd "Sabina directory"/build \n
  optirun ./sabina ../data/"test_name" \n
  
  \subsection NO_Optimus NO_Optimus
  If your computer does not have optimus capabilities you must: \n
  su \n
  cd "Sabina directory"/build \n
  ./sabina ../data/"test_name" \n
	
*/
